---
- name: Install Sublime Text, MySQL Server, and MySQL Workbench on Ubuntu Node
  hosts: ubuntu
  become: yes

  tasks:

    - name: Add Sublime Text APT repository key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add Sublime Text APT repository
      apt_repository:
        repo: 'deb https://download.sublimetext.com/ apt/stable/'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Sublime Text
      apt:
        name: sublime-text
        state: present

    - name: Install Eclipse IDE via Snap
      community.general.snap:
        name: eclipse
        classic: yes
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
    
    - name: Install MySQL Workbench via Snap
      community.general.snap:
        name: mysql-workbench-community
        state: present


    - name: Install PyCharm Community Edition via Snap
      community.general.snap:
        name: pycharm-community
        classic: yes
        state: present

    - name: Install VS Code via Snap
      community.general.snap:
        name: code
        classic: yes
        state: present


