all:
  children:
    windows:
      hosts:
        windows-node1:
          ansible_host: 172.16.51.63
          ansible_user: msis
          ansible_password: "123#msis"
        windows-node2:
          ansible_host: 172.16.51.64
          ansible_user: msis
          ansible_password: "msis"
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore

